### ISSUE TITLE
file can be opened only if it has an extension

### ISSUE THREAD

**Issue by nikgalushko** [moderato-app/approf#3]
First of all, thanks for the tool.

I found a bug :) If a file doesn't have any extension, I cannot open it from Finder or drag and drop it to the app. Only if I add `.pb` can I open it.

**Comment by clement2026** [comment]
@nikgalushko Good spot! That's definitely a bug.

At the moment, approf only supports files with these extensions:
* pb
* gz
* prof
* pprof

Since approf is designed for developers like us, we shouldn’t need to change file extensions just to open them. Let’s allow developers to drag and drop any files into the app and open them directly from Finder

I'll work on fixing this ASAP and will update you once it's done.

Let me know if there's anything else I can help with!

**Comment by clement2026** [comment]
Hey @nikgalushko, v14.1.1 is out. Give it a look!

Upgrade:
```
brew upgrade approf
```

Install:
```bash
brew tap moderato-app/homebrew-brew
brew install approf
```
